apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-platform-config
  namespace: movie-platform
data:
  NODE_ENV: "production"
  PORT: "4000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "movie_booking"
  DB_SSL: "false"
  DB_POOL_MAX: "20"
  CORS_ORIGIN: "*"
